version: 2.1 # Set the CI version.


# We use orbs to provide some common ruby and node tasks and shorten our config.
# Learn more about orbs: https://circleci.com/orbs/
orbs:
  ruby: circleci/ruby@0.1.2
  node: circleci/node@1.1.6


# Yaml References enable us to DRY our our config by sharing variables across multiple jobs.
# In this case, we are commonly using the "workspaces" feature to share
# build artifacts and files across jobs. For example, we build our Javascript
# persist it to a workspace to be made available when the Jekyll site builds.
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root


# Several steps in this config use the same, specialized ruby-caching steps.
# Commands can be used to extract a common set of steps into a reusable-block.
# In this case, whenever you see `- ruby-deps` as a "step" in the config below,
# It is executing a command to restore_cache, install deps if needed, and save_cache.
commands:
  ruby-deps:
    description: "Runs specialized Ruby cache steps."
    steps:
      - restore_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"


jobs:
  js_build:
    executor:
      name: node/default
      tag: '8.11.1'
    steps:
      - *attach_workspace
      - checkout
      - node/with-cache:
          cache-key: "package-lock.json"
          cache-version: v9
          steps:
            - run: npm install
      - run:
          name: "Prepare JS assets" # Compile our final, production-ready JavaScript.
          command: npm run webpack-prod
      - run:
          name: "Persist JS assets" # Moves our JS into our workspace.
          command: |
            set -exu
            mkdir -p /tmp/workspace/js
            mv jekyll/assets/js/*.bundle.js /tmp/workspace/js/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - js

  build_server_pdfs:
    executor:
      name: ruby/default
      tag: '2.6.3-node-browsers'
    steps:
      - *attach_workspace
      - checkout
      - ruby-deps
      - run:
          name: "Create landing folder for PDF output"
          command: mkdir -p /tmp/workspace/pdfs
      - run:
          name: Build PDFs for Server
          command: ./scripts/build_pdfs.sh
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - pdfs

  build_api_docs:
    executor:
      name: ruby/default
      tag: '2.6.3-node-browsers'
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: "Create landing folder for API doc output"
          command: mkdir -p /tmp/workspace/api/v2
      - restore_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "src-api/Gemfile.lock" }}-{{ checksum "src-api/package-lock.json"}}
      - run:
          name: Install ruby dependencies
          command: cd src-api; bundle install
      - run:
          name: Install node dependencies
          command: cd src-api; npm install
      - save_cache:
          key: circleci-docs-{{ checksum "src-api/Gemfile.lock" }}
          paths:
            - src-api/vendor/bundle
            - src-api/node_modules
      - run:
          name: Build API 1.x documentation with Slate
          command: |
            cd src-api; bundle exec middleman build --clean
            cp -R build/* /tmp/workspace/api
      - run:
          name: Build API 2.x documentation with Widdershins and Slate
          command: |
            cd src-api; rm -r build; rm source/index.html.md
            curl https://circleci.com/api/v2/openapi.json > openapi.json
            node node_modules/widdershins/widdershins.js --environment ../widdershins.apiv2.yml --summary openapi.json -o source/index.html.md
            bundle exec middleman build --clean
            cp -R build/* ../jekyll/_api/v2
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - api
      - save_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "src-api/Gemfile.lock" }}
          paths:
            - "src-api/vendor/bundle"

  # The Main "Build" job. It pulls in assets from previous jobs (the built api docs, pdfs and javascript)
  # and puts everything in it's place for a Jekyll build.
  build:
    executor:
      name: ruby/default
      tag: '2.6.3-node-browsers'

    working_directory: ~/circleci-docs
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JOB_RESULTS_PATH: run-results
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: "Test Markdown Files"
          command: ./scripts/test-markdown.sh
      - ruby-deps
      - run:
          name: Create results directory
          command: mkdir -p $JOB_RESULTS_PATH # why do we do this? what is it used for?
      - run:
          name: "Manage Data Files We'll Need"
          command: ./scripts/pull-docker-image-tags.sh
      - run:
          name: Restore Previous Job Assets (Javascript, API docs) to Jekyll directory.
          command: |
            set -exu
            mkdir -p /tmp/workspace/js
            mv /tmp/workspace/js/* jekyll/assets/js/
            mkdir -p /tmp/workspace/api
            cp -r /tmp/workspace/api/* jekyll/_api/
      - run:
          name: Shim untranslated Japanese pages
          command: ./scripts/shim-translation.sh jekyll/_cci2 jekyll/_cci2_ja
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config jekyll/_config.yml,jekyll/_config_production.yml --source jekyll --destination jekyll/_site/docs/ 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt

      ### NOTE: we are ignore some files in the HTML proofer as it fails on pending translated docs.
      - run:
          name: Test with HTMLproofer
          command: bundle exec htmlproofer jekyll/_site --allow-hash-href --check-favicon --check-html --disable-external --file-ignore "/docs/ja/2.0/aws-prereq/,/docs/ja/2.0/ops/,/docs/ja/2.0/about-circleci/,/docs/ja/2.0/demo-apps/,/docs/ja/2.0/google-auth/,/docs/ja/2.0/orb-concepts/,/docs/ja/2.0/tutorials/" --empty-alt-ignore | tee $JOB_RESULTS_PATH/htmlproofer-results.txt

      - store_artifacts: # stores the built files of the Jekyll site
          path: jekyll/_site/docs/
          destination: circleci-docs

      - store_artifacts: # stores build log output.
          path: run-results/
          destination: run-results

      - persist_to_workspace:
          root: ~/circleci-docs/jekyll/_site
          paths:
            - docs

  reindex-search:
    executor:
      name: ruby/default
      tag: '2.6.3-node-browsers'
    working_directory: ~/circleci-docs
    environment:
      JEKYLL_ENV: production
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Update Algolia Index
          command: |
            ALGOLIA_API_KEY=$ALGOLIA_PRIVATE_KEY bundle exec jekyll algolia --source jekyll --config jekyll/_config.yml

  deploy:
    docker:
      - image: cibuilds/aws:1.16.185
    steps:
      - attach_workspace:
          at: ./generated-site
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync generated-site/docs s3://circle-production-static-site/docs/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - js_build
      - build_server_pdfs
      - build_api_docs
      - build:
          requires:
            - js_build
            - build_server_pdfs
            - build_api_docs
      - reindex-search:
          requires:
            - build
          filters:
            branches:
              only: master
      # Can we run a pdf job that only runs on master?
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  nightly-build:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only: master
    jobs:
      - js_build
      - build_api_docs
      - build:
          requires:
            - js_build
            - build_api_docs
      - deploy:
          requires:
            - build
